name: Python Unit Test and PyPI Publish

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install matchlib
        pip install wheel  # Add this line to install 'wheel'
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pytest --junitxml=unittests.xml

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: unittests.xml

    - name: Build Python package distribution
      run: |
        python setup.py sdist
        python setup.py bdist_wheel

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: pypi-AgEIcHlwaS5vcmcCJGQ1NTkzY2EwLWNjY2UtNGJhNy1iMWRkLWI4MTgxM2NjYTM3ZAACKlszLCI3ZDdiZDM1MS1lNmU0LTRkYzQtYWU1NC02OTYwMDYyYjYxNjkiXQAABiDEfrIWxHmaNmf7ROKSIiRp7peg90u3nPdlLL8deFUSeg
      run: |
        python -m pip install --upgrade twine
        python -m twine upload dist/*
