name: Python Unit Test and PyPI Publish

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install matchlib
        pip install build
        pip install wheel  # Add this line to install 'wheel'
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pytest --junitxml=unittests.xml

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: unittests.xml

    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: pypi-AgEIcHlwaS5vcmcCJGYzYTg5ZGUyLWFkMDQtNDMyYS1iYTM4LTM2Y2QzODI1MDdkMAACKlszLCI3ZDdiZDM1MS1lNmU0LTRkYzQtYWU1NC02OTYwMDYyYjYxNjkiXQAABiBFhKZ3dUgmCWiJxR4tBp_BMslQI2811jox-VagQEeTug
